# Sidebar navigation

- label: "Introduction"
  link: "/"
- label: "Prerequisites"
  items:
    - label: "Node"
      link: "prerequisites/node"
    - label: "Modern Javascript"
      link: "prerequisites/modern-js"
- label: "Basics"
  items:
    - label: "Concepts"
      link: "basics/concepts"
    - label: "Setup"
      link: "basics/setup"
    - label: "Components"
      link: "basics/components"
    - label: "State"
      link: "basics/state"
    - label: "Coniditional Rendering and Iterating"
      link: "basics/cond-rendering-iterating"
    - label: "Styling"
      link: "basics/styling"
    - label: "Routing with React Router"
      link: "basics/routing"
    - label: "Example"
      link: "basics/example"
- label: "Next.js"
  items:
    - label: "Introduction"
      link: "next/introduction"
    - label: "Setup"
      link: "next/setup"
    - label: "Routing"
      link: "next/routing"
    - label: "Vercel"
      link: "next/vercel"
- label: "Advanced"
  items:
    - label: "styled-jsx"
      link: "advanced/styled-jsx"
    - label: "HTTP"
      link: "advanced/http"
    - label: "MobX"
      link: "advanced/mobx"
    - label: "Advanced"
      link: "advanced/advanced"
